### ISSUE TITLE
有点问题想请教一下大大优化一下

### ISSUE THREAD

**Issue by Alamoalone** [mengxianliang/XLCardSwitch#1]
就是公司需要类似的效果，但是还有一个多的要求，就是一进页面，会指定某个图片在中间这样显示，是否是使用类似于与collectionview scrollToItemAtIndexPath:<#(nonnull NSIndexPath *)#> atScrollPosition:<#(UICollectionViewScrollPosition)#> animated:<#(BOOL)#>方法，或者selectItemAtIndexPath:<#(nullable NSIndexPath *)#> animated:<#(BOOL)#> scrollPosition:<#(UICollectionViewScrollPosition)#>

**Comment by mengxianliang** [comment]
你好，已经优化了，重新下载一下Demo就可以了。
