### ISSUE TITLE
想在放大的效果上在添加透明度的改变，居中透明度为 1 ，其他为 0.5 ，我应该如何计算alpha

### ISSUE THREAD

**Issue by bruceWangDev** [mengxianliang/XLCardSwitch#10]

**Comment by mengxianliang** [comment]
你可以在XLCardSwitchFlowLayout类中的layoutAttributesForElementsInRect方法中，找到更新中间位置的代码，并修改如下。
（刚刚更新了github上的代码，需要重现下载代码到本地）
![](https://github.com/mengxianliang/ImageRepository/raw/master/Issues/XLCardSwitch/screenshot1.png)

**Comment by bruceWangDev** [comment]
谢谢~！

**Comment by mengxianliang** [comment]
不客气

**Comment by bruceWangDev** [comment]
不好意思我又来了~如果我希望透明度动态的变化，alpha 应该和哪个值相关联？或者说应该如何计算相对应的 alpha

**Comment by mengxianliang** [comment]
直接取scale就行，变化区间是√2/2->1->√2/2，移动到中间透明度最高，移动到两边最小透明度是√2/2。

**Comment by bruceWangDev** [comment]
欧克~我尝试过了 但是有些许不满意，我认为我应该自己摸索一下这个问题~谢谢~
