### ISSUE TITLE
需要刷新数据源时，调用collectionView.reloadData()会导致布局错乱

### ISSUE THREAD

**Issue by sheepshen132** [mengxianliang/XLCardSwitch#13]
如题

**Comment by mengxianliang** [comment]
能否提供一个布局错乱的Demo看一下效果

**Comment by sheepshen132** [comment]
公司项目很赶，不是很方便。解决了，图片数据源切换的时候调collectionView cellForItem(at: indexPath)遍历了一遍cell手动刷新了。这个可能是layoutAttributesForElements的问题，具体不清楚，溜了

**Comment by sheepshen132** [comment]
额，我可能知道了，你demo里在viewDidLoad就获取到具体frame了，我这根据其他页面传入参数在算（变），我把高度定死了也没问题

**Comment by mengxianliang** [comment]
好的👌
