### ISSUE TITLE
能增加无限滚动吗

### ISSUE THREAD

**Issue by Laixg** [mengxianliang/XLCardSwitch#3]
现在的是滑到最后一张就滑不动了 能添加一下无限滚动吗？

**Comment by mengxianliang** [comment]
https://github.com/mengxianliang/XLCycleCollectionView
你好，这是一个无线轮播的例子，里面有实现原理，希望可以帮到你。

**Comment by Laixg** [comment]
今天早上找到了这个demo 试了下 还是有些问题。我再研究下，谢谢
