### ISSUE TITLE
切换时会出现图片的闪动

### ISSUE THREAD

**Issue by Viva5649** [mengxianliang/XLCardSwitch#4]
attributes.transform = CGAffineTransformMakeScale(1.0, scale);只实现了高度的缩放，所以闪动情况不明显。
当把attributes.transform改成attributes.transform = CGAffineTransformMakeScale(scale, scale);的时候，宽度也进行了缩放，闪动情况就更加明显了。
我研究了下，是因为cell重用的机制，导致从缓冲区里拿出来的cell，原先切换时设置的transform被还原了，但是找不到解决方案

**Comment by Viva5649** [comment]
找到问题了，iOS10的锅，iOS10之后给collectionView加了个prefetchingEnabled属性用来提升性能，把这个关掉，就不会出现transform被还原的情况，切换时cell就不会闪动了

**Comment by mengxianliang** [comment]
你好，已经处理好了，代码已经更新。处理方案是在添加缩放动画方法中，扩大一下获取元素的范围，以保证屏幕外一个cell 的宽度内，都能被取到。

即在方法layoutAttributesForElementsInRect中添加如下代码：

    //扩大控制范围，防止出现闪屏现象
    CGRect bigRect = rect;
    bigRect.size.width = rect.size.width + 2*[self cellWidth];
    bigRect.origin.x = rect.origin.x - [self cellWidth];
    
    NSArray *arr = [self getCopyOfAttributes:[super layoutAttributesForElementsInRect:bigRect]];

**Comment by mengxianliang** [comment]
好的，你的方法不错，谢谢啦。
