### ISSUE TITLE
自定义item的大小

### ISSUE THREAD

**Issue by 1253504781** [mengxianliang/XLCardSwitch#5]
博主你好，最近这需要实现这样的一个效果，但是要自定义每个item的大小，collectionView的宽度为屏幕宽度，item大小60*60，你的这个应该怎样定制呢

**Comment by zedxpp** [comment]
XLCardSwitchFlowLayout.m 打开这个文件有惊喜!

**Comment by 1253504781** [comment]
XLCardSwitchFlowLayout.m里面设置了item的大小后就没有那个放大的效果了，所有item都一样大

**Comment by zedxpp** [comment]
我怀疑你改错地方了.  show your code

**Comment by Kingson** [comment]
CardWidthScale的值越小，滑动时放大缩小的效果越不明显
