### ISSUE TITLE
当只有2个卡片时，从第一个卡片滑动到第二个卡片，第二个卡片的点击事件被滑动事件拦截了，卡片大于2个就没有问题了

### ISSUE THREAD

**Issue by Fairy-happy** [mengxianliang/XLCardSwitch#9]
//手指拖动开始
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView {
   
    _dragStartX = scrollView.contentOffset.x;
}

//手指拖动停止
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate {
    if (_pagingEnabled) {return;}
    _dragEndX = scrollView.contentOffset.x;
    dispatch_async(dispatch_get_main_queue(), ^{
        [self fixCellToCenter];
    });
}

被这两个方法拦截了点击事件

**Comment by mengxianliang** [comment]
已经处理了，更新一下代码。
